### ISSUE TITLE
Invisible beds (1.19.2)

### ISSUE THREAD

**Issue by XiNoMiXi** [CCr4ft3r/EnhancedBlockEntitiesReforged#17]
When i put bed on the block, its texture just disappears. is there any config to change bed's stuff for EBE mod?

**Comment by CCr4ft3r** [comment]
There is a config: enhanced_bes.properties. You can try to disable the option: render_enhanced_beds

However I'm also using EBE myself within a large 1.19.2 modpack without any issues. Please check if this issue only appears with only EBE installed. If so please provide your latest.log. If not, it's being caused by another mod.

I'm using EnhancedBlockEntities-Reforged-1.19.2-0.8.0
