### ISSUE TITLE
Chests from expanded storage disappears when far

### ISSUE THREAD

**Issue by gglobensky** [CCr4ft3r/EnhancedBlockEntitiesReforged#18]
The chests from Expanded Storage mods don't seem affected by this mod.
I tested with a vanilla chest and it indeed doensn't disappear, it works as intented.

For info I have tried with the Gold Chest and have the Expanded Storage Woodification resource pack
https://www.curseforge.com/minecraft/texture-packs/expanded-storage-woodification

Here is my modlist:
[modlist.txt](https://github.com/CCr4ft3r/EnhancedBlockEntitiesReforged/files/13539791/modlist.txt)
Forge 43.3.2
Minecraft 1.19.2

Thank you for your awesome work.

**Comment by CCr4ft3r** [comment]
I could reproduce it. But it's acutally not a bug.
Vanilla stops rendering block entities beyond 64 blocks including chests: https://minecraft.fandom.com/wiki/Block_entity#Render_limits

Both chests (vanilla one and the golden one) dissapear beyond that limit with only Expanded Storage installed.
EBE removes this limit for vanilla block entities since with EBE you can render thousands probably ten thousands of chests without performance issues (at least compared to vanilla).

So it's not a bug, it's feature :)
However I think there is a config option in Rubidium/Embeddium to increase the limit.

**Comment by gglobensky** [comment]
Ok, in the pack I use, I have both expanded storage and enhanced block entities.

I noticed the vanilla chest not disappearing while the chests from expanded storage would disappear.
I thought modded chests were expected to be supported, but I guess they are not, which would make sense then.

Expanded Storage's chests are particular because they can merge also on the Y axis to make a 2 tall chest.
Maybe that's what makes it so they aren't supported.
